#!/bin/sh
HMBUTTONCCU2="mh {CONFIG_URL /addons/mh/index.cgi CONFIG_DESCRIPTION {de {<li>Sicherer VPN Fernzugriff</li><li>SMS Versand</li><li>Versand von PUSH Nachrichten</li><li>Mail Versand per Skript</li>} en {<li>Secure VPN remote access</li><li>Send SMS Messages</li><li>Send push notifications</li><li>Send dynamic eMails</li>}} ID mh CONFIG_NAME meine-homematic.de}"
MAILBUTTONCCU2="mh {CONFIG_URL /addons/mh/index.cgi CONFIG_DESCRIPTION {de {<li>Sicherer VPN Fernzugriff</li><li>SMS Versand</li><li>Versand von PUSH Nachrichten</li><li>Mail Versand per Skript</li>} en {<li>Secure VPN remote access</li><li>Send SMS Messages</li><li>Send push notifications</li><li>Send dynamic eMails</li>}} ID mh CONFIG_NAME meine-homematic.de} email {CONFIG_URL /addons/email/index.html CONFIG_DESCRIPTION {de {<li>Email-Integration</li><li>Alarmierung und Weiterleitung von Systemzustaenden</li><li>Einfache Benachrichtigungen</li><li>...</li>} en {<li>Email-Integration</li><li>Alerting and routing of System-States</li><li>Simple Notifications</li><li>...</li>}} ID email CONFIG_NAME Email}"
MAILUNINSTCCU2=" email {CONFIG_URL /addons/email/index.html CONFIG_DESCRIPTION {de {<li>Email-Integration</li><li>Alarmierung und Weiterleitung von Systemzustaenden</li><li>Einfache Benachrichtigungen</li><li>...</li>} en {<li>Email-Integration</li><li>Alerting and routing of System-States</li><li>Simple Notifications</li><li>...</li>}} ID email CONFIG_NAME Email}"

HMBUTTONCCU1="mh {CONFIG_URL /addons/mh/index.cgi CONFIG_DESCRIPTION {<li>VPN-Zugang einrichten</li><li>SMS Versand</li><li>Mail Versand per Skript</li>} ID mh CONFIG_NAME meine-homematic.de}"
MAILBUTTONCCU1="mh {CONFIG_URL /addons/mh/index.cgi CONFIG_DESCRIPTION {<li>VPN-Zugang einrichten</li><li>SMS Versand</li><li>Mail Versand per Skript</li>} ID mh CONFIG_NAME meine-homematic.de} email {CONFIG_URL /addons/email/index.html CONFIG_DESCRIPTION {<li>Email-Integration</li><li>Alarmierung und Weiterleitung von Systemzustaenden</li><li>Einfache Benachrichtigungen</li>} ID email CONFIG_NAME Email}"
MAILUNINSTCCU1=" email {CONFIG_URL /addons/email/index.html CONFIG_DESCRIPTION {<li>Email-Integration</li><li>Alarmierung und Weiterleitung von Systemzustaenden</li><li>Einfache Benachrichtigungen</li>} ID email CONFIG_NAME Email}"
MAILUNINST=""

START_SCRIPT=/etc/config/rc.d/email
WWW_DIR=/etc/config/addons/www/email
ADDON_DIR=/etc/config/addons/email
CONFIG_URL=/addons/email/index.html

case "$1" in
  ""|start)
     grep -i "CCU2" /etc/config/rfd.conf
     if [ $? -eq 0 ]; then
        echo "CCU2"
        mount -o rw,remount /
        mv /usr/local/etc/config/hm_addons.cfg /usr/local/etc/config/hm_addons.cfg_org
        sed -e "s|$HMBUTTONCCU2|$MAILBUTTONCCU2|g" "/usr/local/etc/config/hm_addons.cfg_org" > "/usr/local/etc/config/hm_addons.cfg"
        rm -rf /usr/local/etc/config/hm_addons.cfg_org
        chmod 755 /usr/local/etc/config/hm_addons.cfg
        mount -o ro,remount /
     else
        echo "CCU1"
        mount -o rw,remount /
        mv /usr/local/etc/config/hm_addons.cfg /usr/local/etc/config/hm_addons.cfg_org
        sed -e "s|$HMBUTTONCCU1|$MAILBUTTONCCU1|g" "/usr/local/etc/config/hm_addons.cfg_org" > "/usr/local/etc/config/hm_addons.cfg"
        rm -rf /usr/local/etc/config/hm_addons.cfg_org
        chmod 755 /usr/local/etc/config/hm_addons.cfg
        ln -s /var/log /etc/config/addons/www/email/log
        mount -o ro,remount /
     fi
  ;;

  info)
    VER=`cat /usr/local/etc/config/addons/email/VERSION`
    echo "Info: <b>E-Mail CCU Addon</b><br>"
    echo "Info: (c) 2010-2015 HMside, Jens Maus<br>"
    echo "Info: <a href='https://github.com/jens-maus/hm_email'>https://github.com/jens-maus/hm_email</a>"
    echo "Version: $VER"
    echo "Name: E-Mail"
    echo "Operations: uninstall"
    echo "Config-Url: $CONFIG_URL"
    echo "Update: /addons/email/update-check.cgi"
  ;;

  restart)
  ;;

  stop)
  ;;

  uninstall)
    grep -i "CCU2" /etc/config/rfd.conf
    if [ $? -eq 0 ]; then
      echo "CCU2"
      mount -o rw,remount /
      mv /usr/local/etc/config/hm_addons.cfg /usr/local/etc/config/hm_addons.cfg_org
      sed -e "s|$MAILUNINSTCCU2|$MAILUNINST|g" "/usr/local/etc/config/hm_addons.cfg_org" > "/usr/local/etc/config/hm_addons.cfg"
      rm -rf /usr/local/etc/config/hm_addons.cfg_org
      chmod 755 /usr/local/etc/config/hm_addons.cfg
      sync
      mount -o ro,remount /
    else
      echo "CCU1"
      mount -o rw,remount /
      mv /usr/local/etc/config/hm_addons.cfg /usr/local/etc/config/hm_addons.cfg_org
      sed -e "s|$MAILUNINSTCCU1|$MAILUNINST|g" "/usr/local/etc/config/hm_addons.cfg_org" > "/usr/local/etc/config/hm_addons.cfg"
      rm -rf /usr/local/etc/config/hm_addons.cfg_org
      chmod 755 /usr/local/etc/config/hm_addons.cfg
      sync
      mount -o ro,remount /
    fi
    rm -rf $WWW_DIR
    rm -rf $ADDON_DIR
  ;;

esac

exit 0
