#!/bin/sh

RC_DIR=/usr/local/etc/config/rc.d
WWW_DIR=/usr/local/etc/config/addons/www/email
ADDON_DIR=/usr/local/etc/config/addons/email

if [ "$1" = "" ]; then
  echo "CCU1"
  lcdtool "Installing Addon...   "
  mount -t yaffs /dev/mtdblock3 /usr/local
elif [ "$1" = "CCU2" ]; then
  echo "CCU2"
  mount -t ubifs ubi1:user /usr/local
elif [ "$1" == "HM-RASPBERRYMATIC" ]; then
  echo "HM-RASPBERRYMATIC"
  mount /usr/local
fi

# Startscript anlegen
cp email $RC_DIR/
chmod +x $RC_DIR/email

# Web-Konfiguration anlegen
mkdir -p $WWW_DIR
cp -R www/* $WWW_DIR
chmod 755 $WWW_DIR

# Addon-Verzeichnis anlegen
mkdir -p $ADDON_DIR
cp -R addon/* $ADDON_DIR
chmod 755 $ADDON_DIR

# Konfigdateien und Vorlagen kopieren sofern nicht vorhanden
if [ ! -e $ADDON_DIR/userscript.tcl ]; then
  cp userscript.tcl $ADDON_DIR
fi

if [ ! -e $ADDON_DIR/account.conf ]; then
  cp account.conf $ADDON_DIR
fi

if [ ! -e $ADDON_DIR/msmtp.conf ]; then
  cp msmtp.conf $ADDON_DIR
fi

if [ ! -d $ADDON_DIR/mails ]; then
  cp -R mails $ADDON_DIR/
fi

if [ ! -f $ADDON_DIR/mails/log.mail ]; then
  cp mails/log.mail $ADDON_DIR/mails/log.mail
fi

if [ ! -f $ADDON_DIR/mails/cam.mail ]; then
  cp mails/cam.mail $ADDON_DIR/mails/cam.mail
fi

if [ "$1" = "" ]; then
  cp ccu1/msmtp $ADDON_DIR
elif [ "$1" = "CCU2" ]; then
  cp ccu2/msmtp $ADDON_DIR
elif [ "$1" == "HM-RASPBERRYMATIC" ]; then
  cp ccupi/msmtp $ADDON_DIR
fi

# Alte nicht mehr benötigte Dateien löschen
if [ -e $WWW_DIR/anleitung.html ]; then
  rm -r $WWW_DIR/anleitung.html
fi

if [ -e $WWW_DIR/img/cuxmail.png ]; then
  rm -r $WWW_DIR/img/cuxmail.png
fi

# Symbolic Links
ln -sf $ADDON_DIR/VERSION $WWW_DIR/VERSION.txt
ln -sf $ADDON_DIR $WWW_DIR/addon

# sync filesystem to make sure all changes are written to disk
sync

if [ "$1" = "" ]; then
  echo "CCU1"
  lcdtool "Reboot...             "
  lcdtool -a 0x40 -t bin 00
  echo "x" > /dev/watchdog
  reboot
  while true ; do true ;  done
elif [ "$1" = "CCU2" ]; then
  echo "CCU2"
  # CCU2 always reboots after Addon/Firmware Update
elif [ "$1" = "HM-RASPBERRYMATIC" ]; then
  echo "HM-RASPBERRYMATIC"
  # RASPBERRYMATIC always reboots after Addon/Firmware Update
fi
