#!/bin/sh

ADDON_DIR=/usr/local/etc/config/addons/email

# mount /usr/local if not already mounted
mount | grep /usr/local 2>&1 >/dev/null
if [ $? -eq 1 ]; then
  mount /usr/local
fi

# Vorhandene Dateien löschen
rm -rf /usr/local/etc/config/addons/email/mails
rm -rf /usr/local/etc/config/addons/email/msmtp.conf
rm -rf /usr/local/etc/config/addons/email/account.conf
rm -rf /usr/local/etc/config/addons/email/userscript.tcl

# Dateien aus dem Backup kopieren
cp -af userscript.tcl ${ADDON_DIR}
cp -af account.conf ${ADDON_DIR}
cp -af msmtp.conf ${ADDON_DIR}
cp -af mails ${ADDON_DIR}/

# sync filesystem to make sure all changes are written to disk
sync
